In [1]:
#Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
#might choose one over the other.

In [3]:
#OrdinalEncoder is for converting features, while LabelEncoder is for converting target variable.
#LabelEncoder should be used to encode target values, i.e. y, and not the input X. Ordinal encoding should be used for ordinal 
#variables (where order matters, like cold , warm , hot ); vs Label encoding should be used for non-ordinal variables (where order 
#doesn't matter, like blonde , brunette )

In [4]:
#Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
#a machine learning project.

In [5]:
#Target encoding is the process of replacing a categorical value with the mean of the target variable. Any non-categorical 
#columns are automatically dropped by the target encoder model. Note: You can also use target encoding to convert categorical 
#columns to numeric.
#Seattle can be replaced with average of salary (target variable) of all datapoints where city is Seattle.

In [7]:
#Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

In [8]:
#Covariance is a measure of the relationship between two random variables and to what extent, they change together. Or we can say, 
#in other words, it defines the changes between the two variables, such that change in one variable is equal to change in another 
#variable.
#Covariance is calculated by analyzing at-return surprises (standard deviations from the expected return) or multiplying the
#correlation between the two random variables by the standard deviation of each variable.

In [9]:
#Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
#large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
#Show your code and explain the output.

In [10]:
import pandas as pd

In [14]:
pd.DataFrame({
    'color':['red','green','blue'],
    'size':['small','median','Large'],
    'Material':['wood','metal','plastic']
})

color    size Material
0    red   small     wood
1  green  median    metal
2   blue   Large  plastic

In [16]:
df=pd.DataFrame({
    'color':['red','green','blue'],
    'size':['small','median','Large'],
    'Material':['wood','metal','plastic']
})

In [18]:
df

color    size Material
0    red   small     wood
1  green  median    metal
2   blue   Large  plastic

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
encoder=LabelEncoder()

In [31]:
encoder.fit_transform(df['color'])

array([2, 1, 0])

In [29]:
encoder.fit_transform(df['size'])

array([2, 1, 0])

In [30]:
encoder.fit_transform(df['Material'])

array([2, 0, 1])

In [32]:
#Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
#level. Interpret the results.

In [33]:
data=['Age','Income','Education']

In [34]:
import numpy as np

In [36]:
np.array(data)

array(['Age', 'Income', 'Education'], dtype='<U9')

In [41]:
#Q6. You are working on a machine learning project with a dataset containing several categorical
#variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
#and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
#each variable, and why?

In [42]:
# Here we use Label Encoding Becoz Label Encoding is a popular encoding technique for handling categorical variables. In this 
#technique, each label is assigned a unique integer based on alphabetical ordering.
#In label encoding in Python, we replace the categorical value with a numeric value between 0 and the number of classes minus 1.

In [43]:
#Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
#categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
#East/West). Calculate the covariance between each pair of variables and interpret the results.

In [44]:
import pandas as pd 
import numpy as np

In [51]:
weather_condition=['Sunny','Cludy','Rainy'],
wind_direction=['North','South','East','West']

In [52]:
np.array(weather_condition, wind_direction)

TypeError: Field elements must be 2- or 3-tuples, got ''North''